SvStandardMakefiles = $(CROSS_ROOT)/usr/local/include/SvStandardMakefiles
SvMakefileTemplate = Library
include $(SvStandardMakefiles)/Versions/2/Before.mk

SvName = QBSubsManager
SvDescription = Subtitle manager

SvMajorVersion = 1
SvMinorVersion = 0
SvRevision = 0

SvRequires = SvCore SvFoundation CAGE CUIT QBDataModel3 SvPlayerManager SvPlayerControllers

SvStrictWarnings = yes
CFLAGS += -std=c99


include $(SvStandardMakefiles)/Versions/2/After.mk
