SvName                  ?= $(error $(call SvUndefinedVariable,SvName))
SvDescription           ?= $(error $(call SvUndefinedVariable,SvDescription))
SvMajorVersion          ?= $(error $(call SvUndefinedVariable,SvMajorVersion))
SvMinorVersion          ?= $(error $(call SvUndefinedVariable,SvMinorVersion))
SvRevision              ?= $(error $(call SvUndefinedVariable,SvRevision))
