/*****************************************************************************
** Cubiware Sp. z o.o. Software License Version 1.0
**
** Copyright (C) 2014 Cubiware Sp. z o.o. All rights reserved.
**
** Any rights which are not expressly granted in this License are entirely and
** exclusively reserved to and by Cubiware Sp. z o.o. You may not rent, lease,
** modify, translate, reverse engineer, decompile, disassemble, or create
** derivative works based on this Software. You may not make access to this
** Software available to others in connection with a service bureau,
** application service provider, or similar business, or make any other use of
** this Software without express written permission from Cubiware Sp. z o.o.
**
** Any User wishing to make use of this Software must contact
** Cubiware Sp. z o.o. to arrange an appropriate license. Use of the Software
** includes, but is not limited to:
** (1) integrating or incorporating all or part of the code into a product for
**     sale or license by, or on behalf of, User to third parties;
** (2) distribution of the binary or source code to third parties for use with
**     a commercial product sold or licensed by, or on behalf of, User.
******************************************************************************/

#ifndef QB_CRYPTOGUARD_MENU_H
#define QB_CRYPTOGUARD_MENU_H

/**
 * @file QBCryptoguardMenu.h QBCryptoguardMenu API file
 * @xmlonly<fullDocumentation>This file requires full documentation</fullDocumentation>
 * @endxmlonly
 */

#include <main_decl.h>
#include <QBDataModel3/QBTreePathMap.h>
#include <CUIT/Core/types.h>

/**
 * @defgroup QBCryptoguardMenu Cryptoguard CAS menu
 * @ingroup CubiTV_menus
 *
 * It displays menu generated by Cryptoguard library
 *
 * @{
 */

/**
 * @brief Register QBCryptoguardMenu in main menu tree at given path location
 *
 * @param[in] menuBar menu bar handle
 * @param[in] pathMap path location where menu CryptoguardMenu should be registered
 * @param[in] appGlobals set of application global instances
 */
void QBCryptoguardMenuRegister(SvWidget menuBar, QBTreePathMap pathMap, AppGlobals appGlobals);

/**
* @}
*/

#endif // QB_CRYPTOGUARD_MENU_H
